services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    entrypoint: ./entrypoint.sh
    environment:
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DB_HOST=db
      - DB_PORT=5432

      
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass

  


    